
// // //C:\Web-Development\MyNextjs Journey\tripgraphy\app\layout.tsx
// // //C:\Web-Development\MyNextjs Journey\Copy Tipo graphy\tripgraphy\app\layout.tsx
// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en" className="light">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased `}
// //       >
// //          <Navbar />
// //        <main> {children}</main>
// //       <Footer />
// //       </body>
// //     </html>
// //   );
// // }


// import Navbar from "@/components/navbar";
//  import { Footer } from "@/components/footer";
// import Providers from "@/components/Providers";

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className="light">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
//         <Providers>
//           <Navbar />
//           <main>{children}</main>
//           <Footer />
//         </Providers>
//       </body>
//     </html>
//   );
// }


import "./globals.css";
import Navbar from "@/components/navbar";
import { Footer } from "@/components/footer";
import Providers from "@/components/Providers";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="light">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}